# Generated by Django 5.1.7 on 2025-03-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('batch', models.IntegerField()),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
    ]
