# Generated by Django 5.1.7 on 2025-03-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('ctc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='placementApplication',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('selected', models.BooleanField()),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
